version: '3.7'

services:
  backend:
    container_name: backend
    image: backend:custom
    build: ./backend
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    command: gunicorn --workers=2 --bind=0.0.0.0:8000 backend.wsgi:application
  frontend:
    container_name: frontend
    image: frontend:custom
    build: ./frontend
    restart: unless-stopped
    expose:
      - 3000
    command: serve -s /usr/src/app/build -l 3000
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx:custom
    build: ./nginx
    restart: unless-stopped
    ports:
      - 1337:80
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - frontend

volumes:
  postgres:
    external: true
  static:
    external: false
  media:
    external: true
